2022-04-15 15:08:00,688 ERROR libqtile core.py:get_interesting_pid():L810 Got an exception in getting the window pid
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 571, in wrapper
    return f(*args)
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 658, in wait_for_reply
    self._process_error(error_p[0])
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 645, in _process_error
    self.invalid()
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 559, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/core.py", line 808, in get_interesting_pid
    return win.window.get_net_wm_pid()
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/window.py", line 293, in get_net_wm_pid
    r = self.get_property("_NET_WM_PID", unpack=int)
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/window.py", line 381, in get_property
    ).reply()
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 332, in reply
    data = self.conn.wait_for_reply(self.sequence)
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 573, in wrapper
    self.invalid()
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 559, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.
2022-04-15 15:08:00,790 ERROR libqtile manager.py:_finalize_configurables():L295 exception during finalize
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/core/manager.py", line 283, in _finalize_configurables
    widget.finalize()
  File "/usr/lib/python3.10/site-packages/libqtile/widget/base.py", line 240, in finalize
    self.drawer.finalize()
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/drawer.py", line 35, in finalize
    self._free_pixmap()
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/drawer.py", line 115, in _free_pixmap
    self.qtile.core.conn.conn.core.FreePixmap(self._pixmap)
  File "/usr/lib/python3.10/site-packages/xcffib/xproto.py", line 2863, in FreePixmap
    return self.send_request(54, buf, is_checked=is_checked)
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 391, in send_request
    seq = self.conn.send_request(flags, xcb_parts + 2, xcb_req)
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 569, in wrapper
    self.invalid()
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 559, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.
2022-04-15 15:08:00,791 ERROR libqtile core.py:_xpoll():L327 Shutting down due to X connection error XCB_CONN_ERROR (1)
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/core.py", line 289, in _xpoll
    event = self.conn.conn.poll_for_event()
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 569, in wrapper
    self.invalid()
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 559, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.
2022-04-15 15:08:00,791 ERROR libqtile core.py:get_interesting_pid():L810 Got an exception in getting the window pid
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/core.py", line 289, in _xpoll
    event = self.conn.conn.poll_for_event()
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 569, in wrapper
    self.invalid()
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 559, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/core.py", line 808, in get_interesting_pid
    return win.window.get_net_wm_pid()
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/window.py", line 293, in get_net_wm_pid
    r = self.get_property("_NET_WM_PID", unpack=int)
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/window.py", line 374, in get_property
    r = self.conn.conn.core.GetProperty(
  File "/usr/lib/python3.10/site-packages/xcffib/xproto.py", line 2720, in GetProperty
    return self.send_request(20, buf, GetPropertyCookie, is_checked=is_checked)
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 391, in send_request
    seq = self.conn.send_request(flags, xcb_parts + 2, xcb_req)
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 569, in wrapper
    self.invalid()
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 559, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.
2022-04-15 15:08:00,791 ERROR libqtile core.py:get_interesting_pid():L810 Got an exception in getting the window pid
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/core.py", line 289, in _xpoll
    event = self.conn.conn.poll_for_event()
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 569, in wrapper
    self.invalid()
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 559, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/core.py", line 808, in get_interesting_pid
    return win.window.get_net_wm_pid()
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/window.py", line 293, in get_net_wm_pid
    r = self.get_property("_NET_WM_PID", unpack=int)
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/window.py", line 374, in get_property
    r = self.conn.conn.core.GetProperty(
  File "/usr/lib/python3.10/site-packages/xcffib/xproto.py", line 2720, in GetProperty
    return self.send_request(20, buf, GetPropertyCookie, is_checked=is_checked)
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 391, in send_request
    seq = self.conn.send_request(flags, xcb_parts + 2, xcb_req)
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 569, in wrapper
    self.invalid()
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 559, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.
2022-04-15 15:08:00,791 ERROR libqtile core.py:get_interesting_pid():L810 Got an exception in getting the window pid
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/core.py", line 808, in get_interesting_pid
    return win.window.get_net_wm_pid()
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/window.py", line 293, in get_net_wm_pid
    r = self.get_property("_NET_WM_PID", unpack=int)
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/window.py", line 374, in get_property
    r = self.conn.conn.core.GetProperty(
  File "/usr/lib/python3.10/site-packages/xcffib/xproto.py", line 2720, in GetProperty
    return self.send_request(20, buf, GetPropertyCookie, is_checked=is_checked)
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 391, in send_request
    seq = self.conn.send_request(flags, xcb_parts + 2, xcb_req)
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 569, in wrapper
    self.invalid()
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 559, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.
2022-04-15 15:08:00,791 ERROR libqtile core.py:get_interesting_pid():L810 Got an exception in getting the window pid
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/core.py", line 808, in get_interesting_pid
    return win.window.get_net_wm_pid()
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/window.py", line 293, in get_net_wm_pid
    r = self.get_property("_NET_WM_PID", unpack=int)
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/window.py", line 374, in get_property
    r = self.conn.conn.core.GetProperty(
  File "/usr/lib/python3.10/site-packages/xcffib/xproto.py", line 2720, in GetProperty
    return self.send_request(20, buf, GetPropertyCookie, is_checked=is_checked)
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 391, in send_request
    seq = self.conn.send_request(flags, xcb_parts + 2, xcb_req)
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 569, in wrapper
    self.invalid()
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 559, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.
2022-04-15 15:08:00,792 ERROR libqtile start.py:start():L94 Qtile crashed
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/scripts/start.py", line 92, in start
    q.loop()
  File "/usr/lib/python3.10/site-packages/libqtile/core/manager.py", line 192, in loop
    asyncio.run(self.async_loop())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/usr/lib/python3.10/site-packages/libqtile/core/manager.py", line 220, in async_loop
    self.finalize()
  File "/usr/lib/python3.10/site-packages/libqtile/core/manager.py", line 300, in finalize
    self.core.finalize()
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/core.py", line 165, in finalize
    self.conn.conn.core.DeletePropertyChecked(
  File "/usr/lib/python3.10/site-packages/xcffib/xproto.py", line 2716, in DeleteProperty
    return self.send_request(19, buf, is_checked=is_checked)
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 391, in send_request
    seq = self.conn.send_request(flags, xcb_parts + 2, xcb_req)
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 569, in wrapper
    self.invalid()
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 559, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.
2022-04-15 15:08:00,793 WARNING libqtile lifecycle.py:_atexit():L37 Qtile will now terminate
2022-04-15 15:10:05,644 WARNING libqtile utils.py:send_notification():L246 dbus-next is not installed. Unable to send notifications.
2022-04-15 15:12:08,105 ERROR libqtile manager.py:cmd_reload_config():L260 Configuration error: 'color5'
2022-04-15 15:12:08,105 WARNING libqtile utils.py:send_notification():L246 dbus-next is not installed. Unable to send notifications.
2022-04-15 15:12:09,564 ERROR libqtile manager.py:cmd_reload_config():L260 Configuration error: 'color5'
2022-04-15 15:12:09,564 WARNING libqtile utils.py:send_notification():L246 dbus-next is not installed. Unable to send notifications.
2022-04-15 15:12:09,997 ERROR libqtile manager.py:cmd_reload_config():L260 Configuration error: 'color5'
2022-04-15 15:12:09,997 WARNING libqtile utils.py:send_notification():L246 dbus-next is not installed. Unable to send notifications.
2022-04-15 15:12:11,111 WARNING libqtile lifecycle.py:_atexit():L37 Qtile will now terminate
2022-04-15 15:12:22,171 WARNING libqtile utils.py:send_notification():L246 dbus-next is not installed. Unable to send notifications.
2022-04-15 15:12:47,458 ERROR libqtile manager.py:cmd_reload_config():L260 Configuration error: cannot import name 'widget_defaults' from 'settings.widgets' (/home/jesus/.config/qtile/settings/widgets.py)
2022-04-15 15:12:47,458 WARNING libqtile utils.py:send_notification():L246 dbus-next is not installed. Unable to send notifications.
2022-04-15 15:12:48,712 ERROR libqtile manager.py:cmd_reload_config():L260 Configuration error: cannot import name 'widget_defaults' from 'settings.widgets' (/home/jesus/.config/qtile/settings/widgets.py)
2022-04-15 15:12:48,712 WARNING libqtile utils.py:send_notification():L246 dbus-next is not installed. Unable to send notifications.
2022-04-15 15:12:49,016 ERROR libqtile manager.py:cmd_reload_config():L260 Configuration error: cannot import name 'widget_defaults' from 'settings.widgets' (/home/jesus/.config/qtile/settings/widgets.py)
2022-04-15 15:12:49,016 WARNING libqtile utils.py:send_notification():L246 dbus-next is not installed. Unable to send notifications.
2022-04-15 15:12:49,220 ERROR libqtile manager.py:cmd_reload_config():L260 Configuration error: cannot import name 'widget_defaults' from 'settings.widgets' (/home/jesus/.config/qtile/settings/widgets.py)
2022-04-15 15:12:49,220 WARNING libqtile utils.py:send_notification():L246 dbus-next is not installed. Unable to send notifications.
2022-04-15 15:12:50,491 ERROR libqtile manager.py:cmd_reload_config():L260 Configuration error: cannot import name 'widget_defaults' from 'settings.widgets' (/home/jesus/.config/qtile/settings/widgets.py)
2022-04-15 15:12:50,491 WARNING libqtile utils.py:send_notification():L246 dbus-next is not installed. Unable to send notifications.
2022-04-15 15:12:59,982 ERROR libqtile manager.py:cmd_reload_config():L260 Configuration error: cannot import name 'widget_defaults' from 'settings.widgets' (/home/jesus/.config/qtile/settings/widgets.py)
2022-04-15 15:12:59,982 WARNING libqtile utils.py:send_notification():L246 dbus-next is not installed. Unable to send notifications.
2022-04-15 15:13:03,042 ERROR libqtile manager.py:cmd_reload_config():L260 Configuration error: cannot import name 'widget_defaults' from 'settings.widgets' (/home/jesus/.config/qtile/settings/widgets.py)
2022-04-15 15:13:03,042 WARNING libqtile utils.py:send_notification():L246 dbus-next is not installed. Unable to send notifications.
2022-04-15 15:13:22,863 ERROR libqtile manager.py:cmd_reload_config():L260 Configuration error: cannot import name 'widget_defaults' from 'settings.widgets' (/home/jesus/.config/qtile/settings/widgets.py)
2022-04-15 15:13:22,863 WARNING libqtile utils.py:send_notification():L246 dbus-next is not installed. Unable to send notifications.
2022-04-15 15:13:33,024 ERROR libqtile manager.py:cmd_reload_config():L260 Configuration error: cannot import name 'widget_defaults' from 'settings.widgets' (/home/jesus/.config/qtile/settings/widgets.py)
2022-04-15 15:13:33,024 WARNING libqtile utils.py:send_notification():L246 dbus-next is not installed. Unable to send notifications.
2022-04-15 15:13:34,209 WARNING libqtile lifecycle.py:_atexit():L37 Qtile will now terminate
2022-04-15 15:42:09,965 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-15 15:42:17,136 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-15 15:43:01,077 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-15 15:43:12,960 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-15 15:43:30,349 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-15 15:43:41,037 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-15 15:43:49,928 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-15 15:44:00,051 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-15 15:44:12,929 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-15 15:44:22,480 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-15 15:44:26,029 ERROR libqtile manager.py:process_key_event():L392 KB command error shuffle_up: No such command
2022-04-15 15:44:26,500 ERROR libqtile manager.py:process_key_event():L392 KB command error shuffle_up: No such command
2022-04-15 15:44:26,728 ERROR libqtile manager.py:process_key_event():L392 KB command error shuffle_down: No such command
2022-04-15 15:44:27,033 ERROR libqtile manager.py:process_key_event():L392 KB command error shuffle_down: No such command
2022-04-15 15:44:27,456 ERROR libqtile manager.py:process_key_event():L392 KB command error shuffle_up: No such command
2022-04-15 15:44:27,595 ERROR libqtile manager.py:process_key_event():L392 KB command error shuffle_down: No such command
2022-04-15 15:44:27,712 ERROR libqtile manager.py:process_key_event():L392 KB command error shuffle_up: No such command
2022-04-15 15:44:27,784 ERROR libqtile manager.py:process_key_event():L392 KB command error shuffle_down: No such command
2022-04-15 15:44:27,943 ERROR libqtile manager.py:process_key_event():L392 KB command error shuffle_up: No such command
2022-04-15 15:44:28,044 ERROR libqtile manager.py:process_key_event():L392 KB command error shuffle_down: No such command
2022-04-15 15:44:28,172 ERROR libqtile manager.py:process_key_event():L392 KB command error shuffle_up: No such command
2022-04-15 15:44:28,219 ERROR libqtile manager.py:process_key_event():L392 KB command error shuffle_down: No such command
2022-04-15 15:44:28,678 ERROR libqtile manager.py:process_key_event():L392 KB command error shuffle_down: No such command
2022-04-15 15:44:28,779 ERROR libqtile manager.py:process_key_event():L392 KB command error shuffle_up: No such command
2022-04-15 15:44:28,949 ERROR libqtile manager.py:process_key_event():L392 KB command error shuffle_down: No such command
2022-04-15 15:44:29,045 ERROR libqtile manager.py:process_key_event():L392 KB command error shuffle_up: No such command
2022-04-15 15:44:29,158 ERROR libqtile manager.py:process_key_event():L392 KB command error shuffle_down: No such command
2022-04-15 15:44:29,275 ERROR libqtile manager.py:process_key_event():L392 KB command error shuffle_up: No such command
2022-04-15 15:44:30,182 ERROR libqtile manager.py:process_key_event():L392 KB command error shuffle_up: No such command
2022-04-15 15:44:30,391 ERROR libqtile manager.py:process_key_event():L392 KB command error shuffle_down: No such command
2022-04-15 15:44:30,568 ERROR libqtile manager.py:process_key_event():L392 KB command error shuffle_up: No such command
2022-04-15 15:44:30,676 ERROR libqtile manager.py:process_key_event():L392 KB command error shuffle_down: No such command
2022-04-15 15:44:30,804 ERROR libqtile manager.py:process_key_event():L392 KB command error shuffle_up: No such command
2022-04-15 15:44:30,937 ERROR libqtile manager.py:process_key_event():L392 KB command error shuffle_down: No such command
2022-04-15 15:44:31,054 ERROR libqtile manager.py:process_key_event():L392 KB command error shuffle_up: No such command
2022-04-15 15:44:31,176 ERROR libqtile manager.py:process_key_event():L392 KB command error shuffle_down: No such command
2022-04-15 15:44:31,305 ERROR libqtile manager.py:process_key_event():L392 KB command error shuffle_up: No such command
2022-04-15 15:44:45,308 ERROR libqtile manager.py:process_key_event():L392 KB command error shuffle_up: No such command
2022-04-15 15:44:45,632 ERROR libqtile manager.py:process_key_event():L392 KB command error shuffle_down: No such command
2022-04-15 15:44:45,862 ERROR libqtile manager.py:process_key_event():L392 KB command error shuffle_up: No such command
2022-04-15 15:44:45,996 ERROR libqtile manager.py:process_key_event():L392 KB command error shuffle_down: No such command
2022-04-15 15:44:46,125 ERROR libqtile manager.py:process_key_event():L392 KB command error shuffle_up: No such command
2022-04-15 15:44:46,252 ERROR libqtile manager.py:process_key_event():L392 KB command error shuffle_down: No such command
2022-04-15 15:44:46,386 ERROR libqtile manager.py:process_key_event():L392 KB command error shuffle_up: No such command
2022-04-15 15:44:46,905 ERROR libqtile manager.py:process_key_event():L392 KB command error grow: No such command
2022-04-15 15:44:48,697 ERROR libqtile manager.py:process_key_event():L392 KB command error grow: No such command
2022-04-15 15:44:48,848 ERROR libqtile manager.py:process_key_event():L392 KB command error grow: No such command
2022-04-15 15:44:48,948 ERROR libqtile manager.py:process_key_event():L392 KB command error shrink: No such command
2022-04-15 15:44:49,122 ERROR libqtile manager.py:process_key_event():L392 KB command error shrink: No such command
2022-04-15 15:44:49,270 ERROR libqtile manager.py:process_key_event():L392 KB command error grow: No such command
2022-04-15 15:44:49,369 ERROR libqtile manager.py:process_key_event():L392 KB command error shrink: No such command
2022-04-15 15:44:49,500 ERROR libqtile manager.py:process_key_event():L392 KB command error grow: No such command
2022-04-15 15:44:49,591 ERROR libqtile manager.py:process_key_event():L392 KB command error shrink: No such command
2022-04-15 15:44:49,677 ERROR libqtile manager.py:process_key_event():L392 KB command error grow: No such command
2022-04-15 15:44:49,820 ERROR libqtile manager.py:process_key_event():L392 KB command error shrink: No such command
2022-04-15 15:44:49,941 ERROR libqtile manager.py:process_key_event():L392 KB command error grow: No such command
2022-04-15 15:44:50,043 ERROR libqtile manager.py:process_key_event():L392 KB command error shrink: No such command
2022-04-15 15:44:50,169 ERROR libqtile manager.py:process_key_event():L392 KB command error grow: No such command
2022-04-15 15:44:50,293 ERROR libqtile manager.py:process_key_event():L392 KB command error shrink: No such command
2022-04-15 15:44:50,427 ERROR libqtile manager.py:process_key_event():L392 KB command error grow: No such command
2022-04-15 15:44:50,545 ERROR libqtile manager.py:process_key_event():L392 KB command error shrink: No such command
2022-04-15 15:44:50,703 ERROR libqtile manager.py:process_key_event():L392 KB command error grow: No such command
2022-04-15 15:44:50,790 ERROR libqtile manager.py:process_key_event():L392 KB command error shrink: No such command
2022-04-15 15:44:50,917 ERROR libqtile manager.py:process_key_event():L392 KB command error grow: No such command
2022-04-15 15:44:51,019 ERROR libqtile manager.py:process_key_event():L392 KB command error shrink: No such command
2022-04-15 15:44:51,184 ERROR libqtile manager.py:process_key_event():L392 KB command error grow: No such command
2022-04-15 15:44:51,257 ERROR libqtile manager.py:process_key_event():L392 KB command error shrink: No such command
2022-04-15 15:44:51,393 ERROR libqtile manager.py:process_key_event():L392 KB command error grow: No such command
2022-04-15 15:44:51,480 ERROR libqtile manager.py:process_key_event():L392 KB command error shrink: No such command
2022-04-15 15:44:51,648 ERROR libqtile manager.py:process_key_event():L392 KB command error grow: No such command
2022-04-15 15:44:51,737 ERROR libqtile manager.py:process_key_event():L392 KB command error shrink: No such command
2022-04-15 15:44:51,916 ERROR libqtile manager.py:process_key_event():L392 KB command error grow: No such command
2022-04-15 15:44:52,027 ERROR libqtile manager.py:process_key_event():L392 KB command error shrink: No such command
2022-04-15 15:44:52,189 ERROR libqtile manager.py:process_key_event():L392 KB command error grow: No such command
2022-04-15 15:44:52,295 ERROR libqtile manager.py:process_key_event():L392 KB command error shrink: No such command
2022-04-15 15:44:52,454 ERROR libqtile manager.py:process_key_event():L392 KB command error grow: No such command
2022-04-15 15:44:52,565 ERROR libqtile manager.py:process_key_event():L392 KB command error shrink: No such command
2022-04-15 15:44:52,713 ERROR libqtile manager.py:process_key_event():L392 KB command error grow: No such command
2022-04-15 15:44:52,798 ERROR libqtile manager.py:process_key_event():L392 KB command error shrink: No such command
2022-04-15 15:44:52,988 ERROR libqtile manager.py:process_key_event():L392 KB command error grow: No such command
2022-04-15 15:44:53,031 ERROR libqtile manager.py:process_key_event():L392 KB command error shrink: No such command
2022-04-15 15:44:53,202 ERROR libqtile manager.py:process_key_event():L392 KB command error grow: No such command
2022-04-15 15:44:53,284 ERROR libqtile manager.py:process_key_event():L392 KB command error shrink: No such command
2022-04-15 15:44:53,441 ERROR libqtile manager.py:process_key_event():L392 KB command error grow: No such command
2022-04-15 15:44:53,504 ERROR libqtile manager.py:process_key_event():L392 KB command error shrink: No such command
2022-04-15 15:44:53,639 ERROR libqtile manager.py:process_key_event():L392 KB command error grow: No such command
2022-04-15 15:45:08,070 ERROR libqtile manager.py:process_key_event():L392 KB command error grow: No such command
2022-04-15 15:45:08,215 ERROR libqtile manager.py:process_key_event():L392 KB command error grow: No such command
2022-04-15 15:45:08,436 ERROR libqtile manager.py:process_key_event():L392 KB command error shrink: No such command
2022-04-15 15:45:08,583 ERROR libqtile manager.py:process_key_event():L392 KB command error shrink: No such command
2022-04-15 15:45:08,731 ERROR libqtile manager.py:process_key_event():L392 KB command error shrink: No such command
2022-04-15 15:45:08,862 ERROR libqtile manager.py:process_key_event():L392 KB command error shrink: No such command
2022-04-15 15:45:09,034 ERROR libqtile manager.py:process_key_event():L392 KB command error grow: No such command
2022-04-15 15:45:09,261 ERROR libqtile manager.py:process_key_event():L392 KB command error shrink: No such command
2022-04-15 15:45:09,356 ERROR libqtile manager.py:process_key_event():L392 KB command error grow: No such command
2022-04-15 15:45:09,456 ERROR libqtile manager.py:process_key_event():L392 KB command error shrink: No such command
2022-04-15 15:45:12,471 ERROR libqtile manager.py:process_key_event():L392 KB command error shuffle_up: No such command
2022-04-15 15:45:12,651 ERROR libqtile manager.py:process_key_event():L392 KB command error shuffle_up: No such command
2022-04-15 15:45:12,802 ERROR libqtile manager.py:process_key_event():L392 KB command error shuffle_down: No such command
2022-04-15 15:45:12,947 ERROR libqtile manager.py:process_key_event():L392 KB command error shuffle_up: No such command
2022-04-15 15:45:13,044 ERROR libqtile manager.py:process_key_event():L392 KB command error shuffle_down: No such command
2022-04-15 15:45:13,182 ERROR libqtile manager.py:process_key_event():L392 KB command error shuffle_up: No such command
2022-04-15 15:45:13,290 ERROR libqtile manager.py:process_key_event():L392 KB command error shuffle_down: No such command
2022-04-15 15:45:13,434 ERROR libqtile manager.py:process_key_event():L392 KB command error shuffle_up: No such command
2022-04-15 15:45:13,549 ERROR libqtile manager.py:process_key_event():L392 KB command error shuffle_down: No such command
2022-04-15 15:45:13,682 ERROR libqtile manager.py:process_key_event():L392 KB command error shuffle_up: No such command
2022-04-15 15:45:13,799 ERROR libqtile manager.py:process_key_event():L392 KB command error shuffle_down: No such command
2022-04-15 15:45:13,926 ERROR libqtile manager.py:process_key_event():L392 KB command error shuffle_up: No such command
2022-04-15 15:45:44,990 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-15 15:45:57,185 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-15 15:46:20,388 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-15 15:47:06,994 ERROR libqtile manager.py:process_key_event():L392 KB command error shrink: No such command
2022-04-15 15:47:07,296 ERROR libqtile manager.py:process_key_event():L392 KB command error shrink: No such command
2022-04-15 15:47:08,297 ERROR libqtile manager.py:process_key_event():L392 KB command error grow: No such command
2022-04-15 15:47:08,571 ERROR libqtile manager.py:process_key_event():L392 KB command error grow: No such command
2022-04-15 15:47:08,923 ERROR libqtile manager.py:process_key_event():L392 KB command error grow: No such command
2022-04-15 15:47:09,015 ERROR libqtile manager.py:process_key_event():L392 KB command error shrink: No such command
2022-04-15 15:47:09,165 ERROR libqtile manager.py:process_key_event():L392 KB command error grow: No such command
2022-04-15 15:47:09,250 ERROR libqtile manager.py:process_key_event():L392 KB command error shrink: No such command
2022-04-15 15:47:09,444 ERROR libqtile manager.py:process_key_event():L392 KB command error grow: No such command
2022-04-15 15:47:09,719 ERROR libqtile manager.py:process_key_event():L392 KB command error grow: No such command
2022-04-15 15:47:09,954 ERROR libqtile manager.py:process_key_event():L392 KB command error shrink: No such command
2022-04-15 15:47:10,195 ERROR libqtile manager.py:process_key_event():L392 KB command error grow: No such command
2022-04-15 15:47:10,198 ERROR libqtile manager.py:process_key_event():L392 KB command error shrink: No such command
2022-04-15 15:47:19,794 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-15 15:47:20,398 ERROR libqtile group.py:layout():L128 No such layout: matrix
2022-04-15 15:47:31,637 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-15 15:47:49,623 ERROR libqtile manager.py:process_key_event():L392 KB command error grow: No such command
2022-04-15 15:47:49,802 ERROR libqtile manager.py:process_key_event():L392 KB command error grow: No such command
2022-04-15 15:47:49,970 ERROR libqtile manager.py:process_key_event():L392 KB command error grow: No such command
2022-04-15 15:47:50,671 ERROR libqtile manager.py:process_key_event():L392 KB command error shrink: No such command
2022-04-15 15:47:50,858 ERROR libqtile manager.py:process_key_event():L392 KB command error shrink: No such command
2022-04-15 15:47:51,028 ERROR libqtile manager.py:process_key_event():L392 KB command error grow: No such command
2022-04-15 15:47:51,155 ERROR libqtile manager.py:process_key_event():L392 KB command error shrink: No such command
2022-04-15 15:47:51,271 ERROR libqtile manager.py:process_key_event():L392 KB command error grow: No such command
2022-04-15 15:47:51,377 ERROR libqtile manager.py:process_key_event():L392 KB command error shrink: No such command
2022-04-15 15:47:51,524 ERROR libqtile manager.py:process_key_event():L392 KB command error grow: No such command
2022-04-15 15:47:51,620 ERROR libqtile manager.py:process_key_event():L392 KB command error shrink: No such command
2022-04-15 15:47:51,765 ERROR libqtile manager.py:process_key_event():L392 KB command error grow: No such command
2022-04-15 15:47:51,843 ERROR libqtile manager.py:process_key_event():L392 KB command error shrink: No such command
2022-04-15 15:47:51,976 ERROR libqtile manager.py:process_key_event():L392 KB command error grow: No such command
2022-04-15 15:47:52,056 ERROR libqtile manager.py:process_key_event():L392 KB command error shrink: No such command
2022-04-15 15:47:52,210 ERROR libqtile manager.py:process_key_event():L392 KB command error grow: No such command
2022-04-15 15:47:52,290 ERROR libqtile manager.py:process_key_event():L392 KB command error shrink: No such command
2022-04-15 15:47:52,439 ERROR libqtile manager.py:process_key_event():L392 KB command error grow: No such command
2022-04-15 15:47:52,537 ERROR libqtile manager.py:process_key_event():L392 KB command error shrink: No such command
2022-04-15 15:47:54,537 ERROR libqtile manager.py:process_key_event():L392 KB command error grow: No such command
2022-04-15 15:47:54,693 ERROR libqtile manager.py:process_key_event():L392 KB command error grow: No such command
2022-04-15 15:47:54,840 ERROR libqtile manager.py:process_key_event():L392 KB command error grow: No such command
2022-04-15 15:47:55,062 ERROR libqtile manager.py:process_key_event():L392 KB command error shrink: No such command
2022-04-15 15:47:55,218 ERROR libqtile manager.py:process_key_event():L392 KB command error shrink: No such command
2022-04-15 15:47:55,368 ERROR libqtile manager.py:process_key_event():L392 KB command error shrink: No such command
2022-04-15 15:47:55,663 ERROR libqtile manager.py:process_key_event():L392 KB command error grow: No such command
2022-04-15 15:47:55,820 ERROR libqtile manager.py:process_key_event():L392 KB command error grow: No such command
2022-04-15 15:47:56,016 ERROR libqtile manager.py:process_key_event():L392 KB command error shrink: No such command
2022-04-15 15:47:56,152 ERROR libqtile manager.py:process_key_event():L392 KB command error grow: No such command
2022-04-15 15:47:56,291 ERROR libqtile manager.py:process_key_event():L392 KB command error shrink: No such command
2022-04-15 15:47:56,402 ERROR libqtile manager.py:process_key_event():L392 KB command error grow: No such command
2022-04-15 15:47:56,504 ERROR libqtile manager.py:process_key_event():L392 KB command error shrink: No such command
2022-04-15 15:47:56,604 ERROR libqtile manager.py:process_key_event():L392 KB command error grow: No such command
2022-04-15 15:48:03,771 ERROR libqtile manager.py:process_key_event():L392 KB command error grow: No such command
2022-04-15 15:48:03,938 ERROR libqtile manager.py:process_key_event():L392 KB command error grow: No such command
2022-04-15 15:48:04,098 ERROR libqtile manager.py:process_key_event():L392 KB command error grow: No such command
2022-04-15 15:48:04,354 ERROR libqtile manager.py:process_key_event():L392 KB command error shrink: No such command
2022-04-15 15:48:04,533 ERROR libqtile manager.py:process_key_event():L392 KB command error shrink: No such command
2022-04-15 15:48:04,681 ERROR libqtile manager.py:process_key_event():L392 KB command error shrink: No such command
2022-04-15 15:48:05,136 ERROR libqtile manager.py:process_key_event():L392 KB command error shrink: No such command
2022-04-15 15:48:05,319 ERROR libqtile manager.py:process_key_event():L392 KB command error shrink: No such command
2022-04-15 15:48:07,352 ERROR libqtile manager.py:process_key_event():L392 KB command error shrink: No such command
2022-04-15 15:48:07,546 ERROR libqtile manager.py:process_key_event():L392 KB command error shrink: No such command
2022-04-15 15:48:07,726 ERROR libqtile manager.py:process_key_event():L392 KB command error grow: No such command
2022-04-15 15:48:07,881 ERROR libqtile manager.py:process_key_event():L392 KB command error shrink: No such command
2022-04-15 15:48:07,981 ERROR libqtile manager.py:process_key_event():L392 KB command error grow: No such command
2022-04-15 15:48:08,099 ERROR libqtile manager.py:process_key_event():L392 KB command error shrink: No such command
2022-04-15 15:48:08,225 ERROR libqtile manager.py:process_key_event():L392 KB command error grow: No such command
2022-04-15 15:48:08,319 ERROR libqtile manager.py:process_key_event():L392 KB command error shrink: No such command
2022-04-15 15:48:08,470 ERROR libqtile manager.py:process_key_event():L392 KB command error grow: No such command
2022-04-15 15:48:08,602 ERROR libqtile manager.py:process_key_event():L392 KB command error shrink: No such command
2022-04-15 15:48:08,800 ERROR libqtile manager.py:process_key_event():L392 KB command error grow: No such command
2022-04-15 15:48:08,861 ERROR libqtile manager.py:process_key_event():L392 KB command error shrink: No such command
2022-04-15 15:48:09,050 ERROR libqtile manager.py:process_key_event():L392 KB command error grow: No such command
2022-04-15 15:48:09,109 ERROR libqtile manager.py:process_key_event():L392 KB command error shrink: No such command
2022-04-15 15:48:09,305 ERROR libqtile manager.py:process_key_event():L392 KB command error grow: No such command
2022-04-15 15:48:09,380 ERROR libqtile manager.py:process_key_event():L392 KB command error shrink: No such command
2022-04-15 15:48:09,526 ERROR libqtile manager.py:process_key_event():L392 KB command error grow: No such command
2022-04-15 15:48:09,611 ERROR libqtile manager.py:process_key_event():L392 KB command error shrink: No such command
2022-04-15 15:48:09,754 ERROR libqtile manager.py:process_key_event():L392 KB command error grow: No such command
2022-04-15 15:48:09,857 ERROR libqtile manager.py:process_key_event():L392 KB command error shrink: No such command
2022-04-15 15:48:10,039 ERROR libqtile manager.py:process_key_event():L392 KB command error grow: No such command
2022-04-15 15:48:10,110 ERROR libqtile manager.py:process_key_event():L392 KB command error shrink: No such command
2022-04-15 15:48:10,245 ERROR libqtile manager.py:process_key_event():L392 KB command error grow: No such command
2022-04-15 15:48:10,308 ERROR libqtile manager.py:process_key_event():L392 KB command error shrink: No such command
2022-04-15 15:48:10,418 ERROR libqtile manager.py:process_key_event():L392 KB command error grow: No such command
2022-04-15 15:48:10,493 ERROR libqtile manager.py:process_key_event():L392 KB command error shrink: No such command
2022-04-15 15:48:10,624 ERROR libqtile manager.py:process_key_event():L392 KB command error grow: No such command
2022-04-15 15:48:10,708 ERROR libqtile manager.py:process_key_event():L392 KB command error shrink: No such command
2022-04-15 15:48:10,839 ERROR libqtile manager.py:process_key_event():L392 KB command error grow: No such command
2022-04-15 15:48:10,890 ERROR libqtile manager.py:process_key_event():L392 KB command error shrink: No such command
2022-04-15 15:48:10,999 ERROR libqtile manager.py:process_key_event():L392 KB command error grow: No such command
2022-04-15 15:48:11,100 ERROR libqtile manager.py:process_key_event():L392 KB command error shrink: No such command
2022-04-15 15:48:15,713 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-15 15:48:40,297 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-15 15:49:43,476 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-15 15:50:58,574 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-15 15:51:30,936 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-15 15:51:46,483 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-15 15:51:56,671 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-15 15:52:22,136 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-15 15:53:10,310 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-15 15:53:45,755 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-15 15:55:15,158 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-15 15:55:45,775 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-15 15:56:00,539 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-15 15:56:01,120 ERROR libqtile group.py:layout():L128 No such layout: tile
2022-04-15 16:04:56,346 ERROR libqtile manager.py:process_key_event():L392 KB command error shrink: No such command
2022-04-15 16:04:56,566 ERROR libqtile manager.py:process_key_event():L392 KB command error shrink: No such command
2022-04-15 16:04:56,806 ERROR libqtile manager.py:process_key_event():L392 KB command error shrink: No such command
2022-04-15 16:04:57,047 ERROR libqtile manager.py:process_key_event():L392 KB command error grow: No such command
2022-04-15 16:04:57,220 ERROR libqtile manager.py:process_key_event():L392 KB command error grow: No such command
2022-04-15 16:04:57,385 ERROR libqtile manager.py:process_key_event():L392 KB command error grow: No such command
2022-04-15 16:04:57,500 ERROR libqtile manager.py:process_key_event():L392 KB command error shrink: No such command
2022-04-15 16:04:57,652 ERROR libqtile manager.py:process_key_event():L392 KB command error grow: No such command
2022-04-15 16:04:57,760 ERROR libqtile manager.py:process_key_event():L392 KB command error shrink: No such command
2022-04-15 16:04:57,862 ERROR libqtile manager.py:process_key_event():L392 KB command error grow: No such command
2022-04-15 16:04:58,766 ERROR libqtile manager.py:process_key_event():L392 KB command error grow: No such command
2022-04-15 16:04:58,930 ERROR libqtile manager.py:process_key_event():L392 KB command error grow: No such command
2022-04-15 16:04:59,065 ERROR libqtile manager.py:process_key_event():L392 KB command error shrink: No such command
2022-04-15 16:04:59,217 ERROR libqtile manager.py:process_key_event():L392 KB command error grow: No such command
2022-04-15 16:04:59,305 ERROR libqtile manager.py:process_key_event():L392 KB command error shrink: No such command
2022-04-15 16:05:00,628 ERROR libqtile manager.py:process_key_event():L392 KB command error grow: No such command
2022-04-15 16:05:00,790 ERROR libqtile manager.py:process_key_event():L392 KB command error grow: No such command
2022-04-15 16:05:00,896 ERROR libqtile manager.py:process_key_event():L392 KB command error shrink: No such command
2022-04-15 16:05:01,065 ERROR libqtile manager.py:process_key_event():L392 KB command error shrink: No such command
2022-04-15 16:05:05,033 ERROR libqtile manager.py:process_key_event():L392 KB command error grow: No such command
2022-04-15 16:05:05,210 ERROR libqtile manager.py:process_key_event():L392 KB command error grow: No such command
2022-04-15 16:05:05,343 ERROR libqtile manager.py:process_key_event():L392 KB command error shrink: No such command
2022-04-15 16:05:05,476 ERROR libqtile manager.py:process_key_event():L392 KB command error grow: No such command
2022-04-15 16:05:05,600 ERROR libqtile manager.py:process_key_event():L392 KB command error shrink: No such command
2022-04-15 16:05:05,736 ERROR libqtile manager.py:process_key_event():L392 KB command error grow: No such command
2022-04-15 16:05:05,828 ERROR libqtile manager.py:process_key_event():L392 KB command error shrink: No such command
2022-04-15 16:05:05,952 ERROR libqtile manager.py:process_key_event():L392 KB command error grow: No such command
2022-04-15 16:05:06,042 ERROR libqtile manager.py:process_key_event():L392 KB command error shrink: No such command
2022-04-15 16:08:35,196 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-15 16:08:42,547 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-15 16:09:24,105 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-15 16:09:31,294 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-15 16:09:38,575 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-15 16:09:50,295 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-15 16:10:54,302 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-15 16:11:01,565 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-15 16:11:16,807 ERROR libqtile manager.py:process_key_event():L392 KB command error grow: No such command
2022-04-15 16:11:16,990 ERROR libqtile manager.py:process_key_event():L392 KB command error grow: No such command
2022-04-15 16:11:17,256 ERROR libqtile manager.py:process_key_event():L392 KB command error shrink: No such command
2022-04-15 16:11:17,409 ERROR libqtile manager.py:process_key_event():L392 KB command error grow: No such command
2022-04-15 16:11:17,552 ERROR libqtile manager.py:process_key_event():L392 KB command error shrink: No such command
2022-04-15 16:11:17,663 ERROR libqtile manager.py:process_key_event():L392 KB command error grow: No such command
2022-04-15 16:11:17,774 ERROR libqtile manager.py:process_key_event():L392 KB command error shrink: No such command
2022-04-15 16:11:17,903 ERROR libqtile manager.py:process_key_event():L392 KB command error grow: No such command
2022-04-15 16:11:17,992 ERROR libqtile manager.py:process_key_event():L392 KB command error shrink: No such command
2022-04-15 16:11:18,136 ERROR libqtile manager.py:process_key_event():L392 KB command error grow: No such command
2022-04-15 16:11:18,207 ERROR libqtile manager.py:process_key_event():L392 KB command error shrink: No such command
2022-04-15 16:11:18,328 ERROR libqtile manager.py:process_key_event():L392 KB command error grow: No such command
2022-04-15 16:11:18,437 ERROR libqtile manager.py:process_key_event():L392 KB command error shrink: No such command
2022-04-15 16:12:01,426 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-15 16:13:14,254 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-15 18:30:45,868 ERROR libqtile manager.py:cmd_restart():L1115 Preventing restart because of a configuration error: closing parenthesis ')' does not match opening parenthesis '[' on line 25 (groups.py, line 29)
2022-04-15 18:30:45,868 WARNING libqtile utils.py:send_notification():L246 dbus-next is not installed. Unable to send notifications.
2022-04-15 18:31:02,153 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-15 23:01:49,343 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-15 23:01:51,308 ERROR libqtile hook.py:fire():L391 Error in hook screen_change
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/hook.py", line 389, in fire
    i(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/libqtile/core/manager.py", line 361, in cmd_reconfigure_screens
    self._process_screens()
  File "/usr/lib/python3.10/site-packages/libqtile/core/manager.py", line 342, in _process_screens
    scr._configure(self, i, x, y, w, h, grp, reconfigure_gaps=reconfigure_gaps)
  File "/usr/lib/python3.10/site-packages/libqtile/config.py", line 303, in _configure
    self.set_group(group)
  File "/usr/lib/python3.10/site-packages/libqtile/config.py", line 362, in set_group
    g1 = self.group
AttributeError: 'Screen' object has no attribute 'group'
2022-04-15 23:03:48,344 ERROR libqtile base.py:on_done():L635 Failed to reschedule.
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/widget/base.py", line 627, in on_done
    self.update(result)
  File "/usr/lib/python3.10/site-packages/libqtile/widget/base.py", line 530, in update
    old_width = self.layout.width
  File "/usr/lib/python3.10/site-packages/libqtile/drawer.py", line 81, in width
    return self.layout.get_pixel_size()[0]
  File "/usr/lib/python3.10/site-packages/libqtile/pangocffi.py", line 138, in get_pixel_size
    pango.pango_layout_get_pixel_size(self._pointer, width, height)
TypeError: initializer for ctype 'PangoLayout *' must be a cdata pointer, not NoneType
2022-04-15 23:03:48,345 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-15 23:03:49,704 ERROR libqtile base.py:on_done():L635 Failed to reschedule.
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/widget/base.py", line 627, in on_done
    self.update(result)
  File "/usr/lib/python3.10/site-packages/libqtile/widget/base.py", line 530, in update
    old_width = self.layout.width
  File "/usr/lib/python3.10/site-packages/libqtile/drawer.py", line 81, in width
    return self.layout.get_pixel_size()[0]
  File "/usr/lib/python3.10/site-packages/libqtile/pangocffi.py", line 138, in get_pixel_size
    pango.pango_layout_get_pixel_size(self._pointer, width, height)
TypeError: initializer for ctype 'PangoLayout *' must be a cdata pointer, not NoneType
2022-04-15 23:03:49,705 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-15 23:06:26,251 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-15 23:07:06,093 ERROR libqtile manager.py:process_key_event():L392 KB command error grow: No such command
2022-04-15 23:07:06,337 ERROR libqtile manager.py:process_key_event():L392 KB command error grow: No such command
2022-04-15 23:07:06,517 ERROR libqtile manager.py:process_key_event():L392 KB command error grow: No such command
2022-04-15 23:07:27,355 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-15 23:07:27,911 ERROR libqtile group.py:layout():L128 No such layout: verticaltile
2022-04-15 23:11:04,148 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-15 23:11:19,169 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-15 23:11:39,852 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-15 23:11:55,788 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-15 23:13:30,995 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-15 23:13:38,028 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-15 23:13:44,837 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-15 23:14:02,124 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-15 23:14:06,595 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-15 23:14:12,918 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-15 23:14:19,705 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-15 23:14:23,757 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-15 23:16:54,485 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-15 23:17:19,319 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-15 23:17:34,169 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-15 23:19:20,379 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-15 23:19:25,959 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-15 23:20:13,818 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-15 23:20:18,073 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-15 23:20:29,668 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-15 23:20:34,703 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-15 23:20:40,617 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-15 23:20:46,502 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-15 23:20:56,051 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-15 23:21:03,700 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-15 23:21:08,869 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-15 23:21:16,967 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-15 23:21:37,867 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-15 23:21:52,822 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-15 23:22:01,089 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-15 23:22:12,921 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-15 23:22:51,289 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-15 23:22:58,028 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-15 23:23:02,150 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-15 23:23:19,720 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-15 23:23:26,378 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-15 23:23:33,053 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-15 23:24:21,341 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-15 23:24:33,820 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-15 23:45:18,595 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-15 23:46:10,177 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-15 23:46:46,311 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-15 23:46:57,673 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-15 23:47:05,831 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-15 23:47:34,311 ERROR libqtile manager.py:cmd_restart():L1115 Preventing restart because of a configuration error: libqtile.widget.groupbox.GroupBox() got multiple values for keyword argument 'font'
2022-04-15 23:47:34,311 WARNING libqtile utils.py:send_notification():L246 dbus-next is not installed. Unable to send notifications.
2022-04-15 23:47:36,474 ERROR libqtile manager.py:cmd_restart():L1115 Preventing restart because of a configuration error: libqtile.widget.groupbox.GroupBox() got multiple values for keyword argument 'font'
2022-04-15 23:47:36,474 WARNING libqtile utils.py:send_notification():L246 dbus-next is not installed. Unable to send notifications.
2022-04-15 23:47:36,675 ERROR libqtile manager.py:cmd_restart():L1115 Preventing restart because of a configuration error: libqtile.widget.groupbox.GroupBox() got multiple values for keyword argument 'font'
2022-04-15 23:47:36,676 WARNING libqtile utils.py:send_notification():L246 dbus-next is not installed. Unable to send notifications.
2022-04-15 23:47:36,853 ERROR libqtile manager.py:cmd_restart():L1115 Preventing restart because of a configuration error: libqtile.widget.groupbox.GroupBox() got multiple values for keyword argument 'font'
2022-04-15 23:47:36,853 WARNING libqtile utils.py:send_notification():L246 dbus-next is not installed. Unable to send notifications.
2022-04-15 23:47:37,047 ERROR libqtile manager.py:cmd_restart():L1115 Preventing restart because of a configuration error: libqtile.widget.groupbox.GroupBox() got multiple values for keyword argument 'font'
2022-04-15 23:47:37,047 WARNING libqtile utils.py:send_notification():L246 dbus-next is not installed. Unable to send notifications.
2022-04-15 23:47:43,764 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-15 23:47:59,763 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-15 23:48:43,150 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-15 23:48:53,828 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-15 23:49:03,334 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-15 23:49:26,928 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-15 23:49:33,486 ERROR libqtile base.py:on_done():L635 Failed to reschedule.
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/widget/base.py", line 627, in on_done
    self.update(result)
  File "/usr/lib/python3.10/site-packages/libqtile/widget/base.py", line 530, in update
    old_width = self.layout.width
  File "/usr/lib/python3.10/site-packages/libqtile/drawer.py", line 81, in width
    return self.layout.get_pixel_size()[0]
  File "/usr/lib/python3.10/site-packages/libqtile/pangocffi.py", line 138, in get_pixel_size
    pango.pango_layout_get_pixel_size(self._pointer, width, height)
TypeError: initializer for ctype 'PangoLayout *' must be a cdata pointer, not NoneType
2022-04-15 23:49:33,487 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-15 23:49:53,478 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-15 23:50:05,905 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-15 23:50:12,142 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-15 23:50:38,361 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-15 23:50:49,675 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-15 23:50:59,316 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-15 23:51:23,855 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-15 23:51:30,717 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-15 23:51:58,772 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-15 23:52:18,458 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-15 23:52:25,170 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-15 23:52:43,013 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-15 23:52:50,175 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-15 23:52:55,505 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-15 23:53:00,763 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-15 23:53:10,379 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-15 23:53:44,110 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-15 23:54:09,134 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-15 23:54:18,104 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-15 23:54:23,486 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-15 23:54:33,142 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-15 23:54:42,504 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-15 23:54:53,279 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-15 23:54:58,145 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-15 23:55:03,129 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-15 23:55:08,882 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-15 23:55:17,242 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-15 23:56:00,438 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-15 23:56:18,468 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-15 23:56:28,934 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-15 23:56:35,950 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-15 23:56:41,575 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-15 23:56:46,783 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-15 23:56:55,893 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-15 23:57:02,190 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-15 23:58:09,391 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-15 23:58:10,338 ERROR libqtile base.py:on_done():L623 poll() raised exceptions, not rescheduling
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/widget/base.py", line 620, in on_done
    result = future.result()
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.10/site-packages/libqtile/widget/cpu.py", line 57, in poll
    return self.format.format(**variables)
KeyError: 'MemUsed'
2022-04-15 23:58:10,339 WARNING libqtile base.py:on_done():L637 poll() returned None, not rescheduling
2022-04-15 23:58:17,395 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-15 23:58:18,328 ERROR libqtile base.py:on_done():L623 poll() raised exceptions, not rescheduling
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/widget/base.py", line 620, in on_done
    result = future.result()
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.10/site-packages/libqtile/widget/cpu.py", line 57, in poll
    return self.format.format(**variables)
KeyError: 'MemUsed'
2022-04-15 23:58:18,329 WARNING libqtile base.py:on_done():L637 poll() returned None, not rescheduling
2022-04-15 23:58:22,103 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-15 23:59:39,225 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-16 00:00:10,061 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-16 00:00:20,218 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-16 00:00:48,971 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-16 00:00:55,439 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-16 00:01:39,123 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-16 00:02:07,323 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-16 00:02:53,241 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-16 00:03:09,477 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-16 00:03:24,123 ERROR libqtile manager.py:cmd_restart():L1115 Preventing restart because of a configuration error: cannot import name 'psutil' from 'psutil' (/usr/lib/python3.10/site-packages/psutil/__init__.py)
2022-04-16 00:03:24,123 WARNING libqtile utils.py:send_notification():L246 dbus-next is not installed. Unable to send notifications.
2022-04-16 00:03:25,942 ERROR libqtile manager.py:cmd_restart():L1115 Preventing restart because of a configuration error: cannot import name 'psutil' from 'psutil' (/usr/lib/python3.10/site-packages/psutil/__init__.py)
2022-04-16 00:03:25,942 WARNING libqtile utils.py:send_notification():L246 dbus-next is not installed. Unable to send notifications.
2022-04-16 00:03:29,976 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-16 00:06:46,437 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-16 00:06:47,366 ERROR libqtile base.py:on_done():L623 poll() raised exceptions, not rescheduling
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/widget/base.py", line 620, in on_done
    result = future.result()
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.10/site-packages/libqtile/widget/cpu.py", line 57, in poll
    return self.format.format(**variables)
KeyError: 'psutil'
2022-04-16 00:06:47,366 WARNING libqtile base.py:on_done():L637 poll() returned None, not rescheduling
2022-04-16 00:08:18,964 ERROR libqtile manager.py:cmd_restart():L1115 Preventing restart because of a configuration error: 'load_percent'
2022-04-16 00:08:18,964 WARNING libqtile utils.py:send_notification():L246 dbus-next is not installed. Unable to send notifications.
2022-04-16 00:08:21,047 ERROR libqtile manager.py:cmd_restart():L1115 Preventing restart because of a configuration error: 'load_percent'
2022-04-16 00:08:21,048 WARNING libqtile utils.py:send_notification():L246 dbus-next is not installed. Unable to send notifications.
2022-04-16 00:08:21,364 ERROR libqtile manager.py:cmd_restart():L1115 Preventing restart because of a configuration error: 'load_percent'
2022-04-16 00:08:21,364 WARNING libqtile utils.py:send_notification():L246 dbus-next is not installed. Unable to send notifications.
2022-04-16 00:08:21,563 ERROR libqtile manager.py:cmd_restart():L1115 Preventing restart because of a configuration error: 'load_percent'
2022-04-16 00:08:21,563 WARNING libqtile utils.py:send_notification():L246 dbus-next is not installed. Unable to send notifications.
2022-04-16 00:08:21,768 ERROR libqtile manager.py:cmd_restart():L1115 Preventing restart because of a configuration error: 'load_percent'
2022-04-16 00:08:21,768 WARNING libqtile utils.py:send_notification():L246 dbus-next is not installed. Unable to send notifications.
2022-04-16 00:08:21,952 ERROR libqtile manager.py:cmd_restart():L1115 Preventing restart because of a configuration error: 'load_percent'
2022-04-16 00:08:21,952 WARNING libqtile utils.py:send_notification():L246 dbus-next is not installed. Unable to send notifications.
2022-04-16 00:08:22,139 ERROR libqtile manager.py:cmd_restart():L1115 Preventing restart because of a configuration error: 'load_percent'
2022-04-16 00:08:22,139 WARNING libqtile utils.py:send_notification():L246 dbus-next is not installed. Unable to send notifications.
2022-04-16 00:08:22,339 ERROR libqtile manager.py:cmd_restart():L1115 Preventing restart because of a configuration error: 'load_percent'
2022-04-16 00:08:22,339 WARNING libqtile utils.py:send_notification():L246 dbus-next is not installed. Unable to send notifications.
2022-04-16 00:08:22,565 ERROR libqtile manager.py:cmd_restart():L1115 Preventing restart because of a configuration error: 'load_percent'
2022-04-16 00:08:22,565 WARNING libqtile utils.py:send_notification():L246 dbus-next is not installed. Unable to send notifications.
2022-04-16 00:08:22,978 ERROR libqtile manager.py:cmd_restart():L1115 Preventing restart because of a configuration error: 'load_percent'
2022-04-16 00:08:22,978 WARNING libqtile utils.py:send_notification():L246 dbus-next is not installed. Unable to send notifications.
2022-04-16 00:08:40,444 ERROR libqtile manager.py:cmd_restart():L1115 Preventing restart because of a configuration error: can only concatenate tuple (not "str") to tuple
2022-04-16 00:08:40,444 WARNING libqtile utils.py:send_notification():L246 dbus-next is not installed. Unable to send notifications.
2022-04-16 00:08:41,447 ERROR libqtile manager.py:cmd_restart():L1115 Preventing restart because of a configuration error: can only concatenate tuple (not "str") to tuple
2022-04-16 00:08:41,448 WARNING libqtile utils.py:send_notification():L246 dbus-next is not installed. Unable to send notifications.
2022-04-16 00:08:45,053 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-16 00:08:46,007 ERROR libqtile base.py:on_done():L623 poll() raised exceptions, not rescheduling
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/widget/base.py", line 620, in on_done
    result = future.result()
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.10/site-packages/libqtile/widget/cpu.py", line 57, in poll
    return self.format.format(**variables)
IndexError: Replacement index 0 out of range for positional args tuple
2022-04-16 00:08:46,008 WARNING libqtile base.py:on_done():L637 poll() returned None, not rescheduling
2022-04-16 00:08:58,747 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-16 00:09:03,257 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-16 00:10:41,166 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-16 00:10:51,699 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-16 00:11:21,585 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-16 00:11:31,716 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-16 00:11:37,706 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-16 00:13:22,120 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-16 00:13:25,844 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-16 00:20:03,564 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-16 00:21:31,937 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-16 00:21:36,828 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-16 00:21:50,181 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-16 00:21:55,074 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-16 00:22:00,171 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-16 00:22:05,944 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-16 00:22:11,452 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-16 00:22:16,979 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-16 00:22:21,667 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-16 00:22:26,764 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-16 00:25:18,759 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-16 00:25:19,760 ERROR libqtile base.py:on_done():L623 poll() raised exceptions, not rescheduling
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/widget/base.py", line 620, in on_done
    result = future.result()
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.10/site-packages/libqtile/widget/cpu.py", line 57, in poll
    return self.format.format(**variables)
KeyError: 'freq_current*1000'
2022-04-16 00:25:19,760 WARNING libqtile base.py:on_done():L637 poll() returned None, not rescheduling
2022-04-16 00:25:26,277 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-16 00:25:30,855 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-16 00:26:17,634 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-16 00:26:23,659 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-16 00:27:42,188 ERROR libqtile manager.py:cmd_restart():L1115 Preventing restart because of a configuration error: 'freq_current'
2022-04-16 00:27:42,188 WARNING libqtile utils.py:send_notification():L246 dbus-next is not installed. Unable to send notifications.
2022-04-16 00:27:46,359 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-16 00:28:09,198 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-16 00:28:10,252 ERROR libqtile base.py:on_done():L623 poll() raised exceptions, not rescheduling
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/widget/base.py", line 620, in on_done
    result = future.result()
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.10/site-packages/libqtile/widget/cpu.py", line 57, in poll
    return self.format.format(**variables)
KeyError: 'freq_current * 1000'
2022-04-16 00:28:10,253 WARNING libqtile base.py:on_done():L637 poll() returned None, not rescheduling
2022-04-16 00:28:55,581 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-16 00:30:27,893 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-16 00:30:34,407 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-16 00:30:35,409 ERROR libqtile base.py:on_done():L623 poll() raised exceptions, not rescheduling
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/widget/base.py", line 620, in on_done
    result = future.result()
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.10/site-packages/libqtile/widget/cpu.py", line 57, in poll
    return self.format.format(**variables)
ValueError: Single '}' encountered in format string
2022-04-16 00:30:35,409 WARNING libqtile base.py:on_done():L637 poll() returned None, not rescheduling
2022-04-16 00:34:17,734 ERROR libqtile manager.py:cmd_restart():L1115 Preventing restart because of a configuration error: 'load_percent'
2022-04-16 00:34:17,734 WARNING libqtile utils.py:send_notification():L246 dbus-next is not installed. Unable to send notifications.
2022-04-16 00:34:18,771 ERROR libqtile manager.py:cmd_restart():L1115 Preventing restart because of a configuration error: 'load_percent'
2022-04-16 00:34:18,771 WARNING libqtile utils.py:send_notification():L246 dbus-next is not installed. Unable to send notifications.
2022-04-16 00:34:19,023 ERROR libqtile manager.py:cmd_restart():L1115 Preventing restart because of a configuration error: 'load_percent'
2022-04-16 00:34:19,023 WARNING libqtile utils.py:send_notification():L246 dbus-next is not installed. Unable to send notifications.
2022-04-16 00:34:19,244 ERROR libqtile manager.py:cmd_restart():L1115 Preventing restart because of a configuration error: 'load_percent'
2022-04-16 00:34:19,244 WARNING libqtile utils.py:send_notification():L246 dbus-next is not installed. Unable to send notifications.
2022-04-16 00:34:19,467 ERROR libqtile manager.py:cmd_restart():L1115 Preventing restart because of a configuration error: 'load_percent'
2022-04-16 00:34:19,467 WARNING libqtile utils.py:send_notification():L246 dbus-next is not installed. Unable to send notifications.
2022-04-16 00:34:19,694 ERROR libqtile manager.py:cmd_restart():L1115 Preventing restart because of a configuration error: 'load_percent'
2022-04-16 00:34:19,695 WARNING libqtile utils.py:send_notification():L246 dbus-next is not installed. Unable to send notifications.
2022-04-16 00:34:33,518 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-16 00:34:42,811 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-16 00:34:50,955 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-16 00:34:51,527 ERROR libqtile bar.py:_configure_widget():L340 CPU widget crashed during _configure with error: KeyError('load_percent')
2022-04-16 00:34:51,964 ERROR libqtile base.py:on_done():L635 Failed to reschedule.
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/widget/base.py", line 627, in on_done
    self.update(result)
  File "/usr/lib/python3.10/site-packages/libqtile/widget/base.py", line 530, in update
    old_width = self.layout.width
AttributeError: 'NoneType' object has no attribute 'width'
2022-04-16 00:34:57,918 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-16 00:34:58,488 ERROR libqtile bar.py:_configure_widget():L340 CPU widget crashed during _configure with error: KeyError('load_percent')
2022-04-16 00:34:58,953 ERROR libqtile base.py:on_done():L635 Failed to reschedule.
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/widget/base.py", line 627, in on_done
    self.update(result)
  File "/usr/lib/python3.10/site-packages/libqtile/widget/base.py", line 530, in update
    old_width = self.layout.width
AttributeError: 'NoneType' object has no attribute 'width'
2022-04-16 00:35:09,422 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-16 00:35:30,093 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-16 00:35:30,676 ERROR libqtile bar.py:_configure_widget():L340 CPU widget crashed during _configure with error: IndexError('Replacement index 1 out of range for positional args tuple')
2022-04-16 00:35:31,187 ERROR libqtile base.py:on_done():L635 Failed to reschedule.
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/widget/base.py", line 627, in on_done
    self.update(result)
  File "/usr/lib/python3.10/site-packages/libqtile/widget/base.py", line 530, in update
    old_width = self.layout.width
AttributeError: 'NoneType' object has no attribute 'width'
2022-04-16 00:35:34,525 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-16 00:35:41,360 ERROR libqtile manager.py:cmd_restart():L1115 Preventing restart because of a configuration error: unsupported operand type(s) for +: 'int' and 'str'
2022-04-16 00:35:41,360 WARNING libqtile utils.py:send_notification():L246 dbus-next is not installed. Unable to send notifications.
2022-04-16 00:35:42,148 ERROR libqtile manager.py:cmd_restart():L1115 Preventing restart because of a configuration error: unsupported operand type(s) for +: 'int' and 'str'
2022-04-16 00:35:42,148 WARNING libqtile utils.py:send_notification():L246 dbus-next is not installed. Unable to send notifications.
2022-04-16 00:35:46,538 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-16 00:36:03,776 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-16 00:36:10,881 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-16 00:36:54,969 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-16 00:37:08,791 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-16 00:37:57,708 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-16 00:38:00,583 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-16 00:38:22,259 ERROR libqtile manager.py:cmd_restart():L1115 Preventing restart because of a configuration error: invalid syntax. Perhaps you forgot a comma? (widgets.py, line 99)
2022-04-16 00:38:22,259 WARNING libqtile utils.py:send_notification():L246 dbus-next is not installed. Unable to send notifications.
2022-04-16 00:38:36,065 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-16 00:38:36,574 WARNING libqtile utils.py:send_notification():L246 dbus-next is not installed. Unable to send notifications.
2022-04-16 00:38:36,601 ERROR libqtile group.py:layout():L128 No such layout: monadtall
2022-04-16 00:38:36,603 ERROR libqtile group.py:layout():L128 No such layout: monadtall
2022-04-16 00:38:43,934 ERROR libqtile manager.py:cmd_reload_config():L260 Configuration error: 'float' object has no attribute 'time'
2022-04-16 00:38:43,934 WARNING libqtile utils.py:send_notification():L246 dbus-next is not installed. Unable to send notifications.
2022-04-16 00:38:45,154 ERROR libqtile manager.py:cmd_reload_config():L260 Configuration error: 'float' object has no attribute 'time'
2022-04-16 00:38:45,154 WARNING libqtile utils.py:send_notification():L246 dbus-next is not installed. Unable to send notifications.
2022-04-16 00:38:45,392 ERROR libqtile manager.py:cmd_reload_config():L260 Configuration error: 'float' object has no attribute 'time'
2022-04-16 00:38:45,392 WARNING libqtile utils.py:send_notification():L246 dbus-next is not installed. Unable to send notifications.
2022-04-16 00:38:45,568 ERROR libqtile manager.py:cmd_reload_config():L260 Configuration error: 'float' object has no attribute 'time'
2022-04-16 00:38:45,568 WARNING libqtile utils.py:send_notification():L246 dbus-next is not installed. Unable to send notifications.
2022-04-16 00:38:45,757 ERROR libqtile manager.py:cmd_reload_config():L260 Configuration error: 'float' object has no attribute 'time'
2022-04-16 00:38:45,757 WARNING libqtile utils.py:send_notification():L246 dbus-next is not installed. Unable to send notifications.
2022-04-16 00:38:52,304 ERROR libqtile manager.py:cmd_reload_config():L260 Configuration error: 'float' object has no attribute 'time'
2022-04-16 00:38:52,305 WARNING libqtile utils.py:send_notification():L246 dbus-next is not installed. Unable to send notifications.
2022-04-16 00:39:41,568 ERROR libqtile manager.py:cmd_reload_config():L260 Configuration error: 'float' object has no attribute 'time'
2022-04-16 00:39:41,568 WARNING libqtile utils.py:send_notification():L246 dbus-next is not installed. Unable to send notifications.
2022-04-16 00:39:41,943 ERROR libqtile manager.py:cmd_reload_config():L260 Configuration error: 'float' object has no attribute 'time'
2022-04-16 00:39:41,944 WARNING libqtile utils.py:send_notification():L246 dbus-next is not installed. Unable to send notifications.
2022-04-16 00:39:42,120 ERROR libqtile manager.py:cmd_reload_config():L260 Configuration error: 'float' object has no attribute 'time'
2022-04-16 00:39:42,120 WARNING libqtile utils.py:send_notification():L246 dbus-next is not installed. Unable to send notifications.
2022-04-16 00:39:42,289 ERROR libqtile manager.py:cmd_reload_config():L260 Configuration error: 'float' object has no attribute 'time'
2022-04-16 00:39:42,290 WARNING libqtile utils.py:send_notification():L246 dbus-next is not installed. Unable to send notifications.
2022-04-16 00:39:42,465 ERROR libqtile manager.py:cmd_reload_config():L260 Configuration error: 'float' object has no attribute 'time'
2022-04-16 00:39:42,466 WARNING libqtile utils.py:send_notification():L246 dbus-next is not installed. Unable to send notifications.
2022-04-16 00:39:42,654 ERROR libqtile manager.py:cmd_reload_config():L260 Configuration error: 'float' object has no attribute 'time'
2022-04-16 00:39:42,654 WARNING libqtile utils.py:send_notification():L246 dbus-next is not installed. Unable to send notifications.
2022-04-16 00:39:42,821 ERROR libqtile manager.py:cmd_reload_config():L260 Configuration error: 'float' object has no attribute 'time'
2022-04-16 00:39:42,822 WARNING libqtile utils.py:send_notification():L246 dbus-next is not installed. Unable to send notifications.
2022-04-16 00:39:43,021 ERROR libqtile manager.py:cmd_reload_config():L260 Configuration error: 'float' object has no attribute 'time'
2022-04-16 00:39:43,021 WARNING libqtile utils.py:send_notification():L246 dbus-next is not installed. Unable to send notifications.
2022-04-16 00:39:43,204 ERROR libqtile manager.py:cmd_reload_config():L260 Configuration error: 'float' object has no attribute 'time'
2022-04-16 00:39:43,205 WARNING libqtile utils.py:send_notification():L246 dbus-next is not installed. Unable to send notifications.
2022-04-16 00:39:49,826 WARNING libqtile lifecycle.py:_atexit():L37 Qtile will now terminate
2022-04-16 00:51:26,579 ERROR libqtile base.py:on_done():L635 Failed to reschedule.
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/widget/base.py", line 627, in on_done
    self.update(result)
  File "/usr/lib/python3.10/site-packages/libqtile/widget/base.py", line 530, in update
    old_width = self.layout.width
  File "/usr/lib/python3.10/site-packages/libqtile/drawer.py", line 81, in width
    return self.layout.get_pixel_size()[0]
  File "/usr/lib/python3.10/site-packages/libqtile/pangocffi.py", line 138, in get_pixel_size
    pango.pango_layout_get_pixel_size(self._pointer, width, height)
TypeError: initializer for ctype 'PangoLayout *' must be a cdata pointer, not NoneType
2022-04-16 00:51:26,581 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-16 00:51:38,672 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-16 00:52:23,340 ERROR libqtile manager.py:cmd_restart():L1115 Preventing restart because of a configuration error: attempted relative import beyond top-level package
2022-04-16 00:52:23,340 WARNING libqtile utils.py:send_notification():L246 dbus-next is not installed. Unable to send notifications.
2022-04-16 00:52:25,124 ERROR libqtile manager.py:cmd_restart():L1115 Preventing restart because of a configuration error: attempted relative import beyond top-level package
2022-04-16 00:52:25,125 WARNING libqtile utils.py:send_notification():L246 dbus-next is not installed. Unable to send notifications.
2022-04-16 00:52:29,036 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-16 00:53:03,600 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-16 00:56:00,374 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-16 00:56:38,361 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-16 00:56:39,435 ERROR libqtile base.py:on_done():L623 poll() raised exceptions, not rescheduling
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/widget/base.py", line 620, in on_done
    result = future.result()
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.10/site-packages/libqtile/widget/cpu.py", line 57, in poll
    return self.format.format(**variables)
KeyError: 'freq'
2022-04-16 00:56:39,435 WARNING libqtile base.py:on_done():L637 poll() returned None, not rescheduling
2022-04-16 00:56:44,248 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-16 00:56:56,536 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-16 01:06:13,184 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-16 01:07:34,187 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-16 01:08:03,081 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-16 01:08:08,340 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-16 01:17:10,951 ERROR libqtile manager.py:process_key_event():L392 KB command error grow: No such command
2022-04-16 01:17:11,301 ERROR libqtile manager.py:process_key_event():L392 KB command error grow: No such command
2022-04-16 01:17:11,431 ERROR libqtile manager.py:process_key_event():L392 KB command error shrink: No such command
2022-04-16 01:17:11,584 ERROR libqtile manager.py:process_key_event():L392 KB command error grow: No such command
2022-04-16 01:17:11,731 ERROR libqtile manager.py:process_key_event():L392 KB command error shrink: No such command
2022-04-16 01:17:11,847 ERROR libqtile manager.py:process_key_event():L392 KB command error grow: No such command
2022-04-16 01:17:11,955 ERROR libqtile manager.py:process_key_event():L392 KB command error shrink: No such command
2022-04-16 01:17:12,069 ERROR libqtile manager.py:process_key_event():L392 KB command error grow: No such command
2022-04-16 01:17:12,226 ERROR libqtile manager.py:process_key_event():L392 KB command error shrink: No such command
2022-04-16 01:17:12,374 ERROR libqtile manager.py:process_key_event():L392 KB command error grow: No such command
2022-04-16 01:17:12,508 ERROR libqtile manager.py:process_key_event():L392 KB command error shrink: No such command
2022-04-16 01:17:44,680 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-16 01:17:45,276 ERROR libqtile group.py:layout():L128 No such layout: spiral
2022-04-16 01:20:49,497 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-16 01:21:06,475 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-16 01:21:07,028 ERROR libqtile bar.py:_configure_widget():L340 CPU widget crashed during _configure with error: IndexError('Replacement index 1 out of range for positional args tuple')
2022-04-16 01:21:07,577 ERROR libqtile base.py:on_done():L635 Failed to reschedule.
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/widget/base.py", line 627, in on_done
    self.update(result)
  File "/usr/lib/python3.10/site-packages/libqtile/widget/base.py", line 530, in update
    old_width = self.layout.width
AttributeError: 'NoneType' object has no attribute 'width'
2022-04-16 01:21:13,549 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-16 01:21:19,883 ERROR libqtile manager.py:cmd_restart():L1115 Preventing restart because of a configuration error: Replacement index 0 out of range for positional args tuple
2022-04-16 01:21:19,883 WARNING libqtile utils.py:send_notification():L246 dbus-next is not installed. Unable to send notifications.
2022-04-16 01:21:22,812 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-16 01:22:21,194 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-16 01:31:02,553 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-16 01:54:49,785 ERROR libqtile base.py:on_done():L635 Failed to reschedule.
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/widget/base.py", line 627, in on_done
    self.update(result)
  File "/usr/lib/python3.10/site-packages/libqtile/widget/base.py", line 530, in update
    old_width = self.layout.width
  File "/usr/lib/python3.10/site-packages/libqtile/drawer.py", line 81, in width
    return self.layout.get_pixel_size()[0]
  File "/usr/lib/python3.10/site-packages/libqtile/pangocffi.py", line 138, in get_pixel_size
    pango.pango_layout_get_pixel_size(self._pointer, width, height)
TypeError: initializer for ctype 'PangoLayout *' must be a cdata pointer, not NoneType
2022-04-16 01:54:49,787 WARNING libqtile lifecycle.py:_atexit():L37 Qtile will now terminate
2022-04-16 01:58:27,792 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-16 01:58:49,839 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-04-16 01:58:50,690 ERROR libqtile base.py:on_done():L623 poll() raised exceptions, not rescheduling
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/widget/base.py", line 620, in on_done
    result = future.result()
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.10/site-packages/libqtile/widget/cpu.py", line 57, in poll
    return self.format.format(**variables)
IndexError: Replacement index 0 out of range for positional args tuple
2022-04-16 01:58:50,691 WARNING libqtile base.py:on_done():L637 poll() returned None, not rescheduling
2022-04-16 01:59:02,447 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
